### PR TITLE
Final Milestone

### PR DESCRIPTION
**Pull request by yetemegn-telaye**
### Capstone React final milestone

In this milestone I:

-  Created basic file structure of the app and setup project
- Created the routing structure of the app
- Fetched data from the api using reducers
- Displayed the fetched data of coins in home component
- Implemented live search functionality with coin name in home component
- Implemented navigation to coinDetail component to display the clicked coin's detail data
- Styled all the components
- Tested  functions 

Loom video link: https://www.loom.com/share/9d9c9ecf0653467ea552be6cfda31e08

### CODE REVIEW

**Review by andersonlebon — CHANGES_REQUESTED** [review]
### Hello @yetemegn-telaye 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

almost-there
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
# Required Changes ♻️

- [ ] Kindly make sure the Live Demo link in the README file is working, because I'm getting a message error. let's fix it :smiley: 

Screenshot from 2022-12-09 03-00-54


- [x] Your Video is fine :+1: but you still need to fix one part. Kindly add some pieces of code to your video. Let's add it :+1: 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

**Comment by yetemegn-telaye** [comment]
Hello @andersonlebon , thank you very much for the descriptive review on my PR. I just wanted to ask you how I can fix my deploy of the site on netlify. It says that it is successfully published and it gave me a link but the link seems to be empty.
link: https://resplendent-donut-91ceeb.netlify.app/
Could you please help me on that?
 Thank you again!

**Review by AmaduKamara — APPROVED** [review]
# Status: Approved 🟢🟢🟢 

Hi @yetemegn-telaye,

Your project is complete!  

ClappingLeonardoDicaprioGIF (4)

## Highlights:
✅ You used Gitlow correctly 👍 
✅ Linter checks passed 👍 
✅ Good descriptive PR 👍 
✅ App works fine as expected 👍 
✅ Good video presentation 👍 
✅ Test passed 👍 

## Recommendation 

- [ ] Your app works fine locally and everything was as expected. I don't think the hosting problem is from you, but I recommend you re-deploy your app again later for potential employers should one end up checking your repositories. 👍 

There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by yetemegn-telaye** [comment]
Hi @AmaduKamara, thank you so much for thoroughly working on this issue with me. I will definitely keep working on this deploy issue after this.

**Pull request merged**
